#pragma once

#include"LibError.hpp"
#include"LibGenerator.hpp"

#include<fstream>
#include<string>

/// @brief This function will check if name given by user has got ".txt" extension
/// @param name name of file given by user
/// @return string with ".txt" extension (if not have before)
std::string f_check_if_txt(std::string name);

/// @brief This function will open file to write in
/// @param file_name file name we want to open
/// @param file variable of file we want to operate on
void f_open_file_write(std::string file_name, std::ofstream& file);

/// @brief This function will save generated numbers, which solves a linear equation by the congruence method to file
/// @param num_range range of numbers
/// @param num_numb numbers
/// @param first_numb value of seed (x0)
/// @param file_name name of output file
void f_save_to_file_linear(int num_range, int num_numb, int first_numb, std::string file_name);

/// @brief This function will open file to read from
/// @param file_name file name we want to open
/// @param file variable of file we want to operate on
void f_open_file_read(std::string file_name, std::ifstream& file);

/// @brief This function will search for best match pairs by reading information from a file and then writing it to array
/// @param file_name name of file we want to read from
/// @param size_array size of array
/// @return addres of array with 2 elements (a pair)
int* f_search_pairs(std::string file_name, int size_array);

/// @brief This function will save numbers generated by congruent method to file
/// @param y_array addres to y array
/// @param size_array size of y array
void f_save_to_file_addictive(int* y_array, int size_array);
